include_guard(GLOBAL)

# generator specified architecture
if(MSVC AND CMAKE_GENERATOR_PLATFORM)
    if("${CMAKE_GENERATOR_PLATFORM}" MATCHES "(Win32|win32)$")
        set(CMAKE_SYSTEM_PROCESSOR X86)
    elseif("${CMAKE_GENERATOR_PLATFORM}" MATCHES "(ARM64|arm64)$")
        set(CMAKE_SYSTEM_PROCESSOR ARM64)
    else()
        set(CMAKE_SYSTEM_PROCESSOR AMD64)
    endif()
endif()

if(MSVC AND SYSTEM_PROCESSOR)
    if("${SYSTEM_PROCESSOR}" MATCHES "x86")
        set(CMAKE_SYSTEM_PROCESSOR X86)
    elseif("${SYSTEM_PROCESSOR}" MATCHES "(ARM64|arm64)$")
        set(CMAKE_SYSTEM_PROCESSOR ARM64)
    else()
        set(CMAKE_SYSTEM_PROCESSOR AMD64)
    endif()
endif()

if("${CMAKE_SYSTEM_PROCESSOR}" MATCHES "(x86|X86|i686|i386)$")
    set(ARCH "x86")
    if(WIN32)
        set(LIB_ARCH "x86")
    elseif(UNIX AND NOT APPLE)
        set(LIB_ARCH "i386")
    endif()
elseif("${CMAKE_SYSTEM_PROCESSOR}" MATCHES "(arm64|ARM64|aarch64)$")
    set(ARCH "arm64")
    if(WIN32)
        set(LIB_ARCH "arm64")
    elseif(UNIX AND NOT APPLE)
        set(LIB_ARCH "aarch64")
    endif()
elseif("${CMAKE_SYSTEM_PROCESSOR}" MATCHES "(amd64|AMD64|x86_64)$")
    set(ARCH "x86_64")
    if(WIN32)
        set(LIB_ARCH "x64")
    elseif(UNIX AND NOT APPLE)
        set(LIB_ARCH "x86_64")
    endif()
else()
    message(FATAL_ERROR "Unsupported Architecture ${CMAKE_SYSTEM_PROCESSOR}")
endif()

if(NOT ARCH)
    message(FATAL_ERROR "Architecture detection failed")
endif()
