name: build

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths-ignore:
      - '**.md'
      - '*.txt'
      - '.gitignore'
      - 'docs/*'
  pull_request:
    branches: [master]
    paths-ignore:
      - '**.md'
      - '*.txt'
      - '.gitignore'
      - 'docs/*'
  release:
    types: [published]

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        arch: [x86, x86_64]
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        if [ ${{ matrix.arch }} == "x86" ]; then
          sudo dpkg --add-architecture i386
          sudo apt-get -qq update
          sudo apt-get -y install aptitude
          sudo apt-get -y install gcc-multilib g++-multilib ninja-build
          sudo apt-get -y install --allow-downgrades libpcre2-8-0:i386 libjpeg-dev:i386 libcurl4-openssl-dev:i386
          sudo aptitude -y install libglib2.0-dev:i386 libsdl2-dev:i386
        else
          sudo apt-get -qq update
          sudo apt-get -y install ninja-build libjpeg-dev libsdl2-dev libcurl4-openssl-dev
        fi
    - name: Compile
      run: |
        if [ ${{ matrix.arch }} == "x86" ]; then
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DUSE_SDL2=TRUE -DUSE_SDL3=OFF -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/cross-x86-linux.cmake
        else
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DUSE_SDL2=TRUE -DUSE_SDL3=OFF
        fi
        cmake --build build
    #- name: Upload
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: ${{ github.event.repository.name }}-linux-${{ needs.versions.outputs.base }}
    #    path: |
    #      build/Release/**/*
  windows-msvc:
    name: Windows MSVC
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        arch: [Win32, x64]
    steps:
    - uses: actions/checkout@v4
    - name: Compile
      run: |
        cmake -S . -B build -G "Visual Studio 17 2022" -A "${{ matrix.arch }}"
        cmake --build build --config Release
    #- name: Upload
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: ${{ github.event.repository.name }}-windows-msvc-${{ needs.versions.outputs.base }}
    #    path: |
    #      build/Release/**/*.dll
    #      build/Release/**/*.exe
  windows-mingw:
    name: Windows MinGW
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        arch: [x86, x86_64]
    steps:
    - uses: actions/checkout@v4
    - name: Compile
      run: |
        if ($env:arch -eq 'x86') {
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/cross-mingw-x86-windows.cmake
        } else {
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
        }
        cmake --build build
    #- name: Upload
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: ${{ github.event.repository.name }}-windows-mingw-${{ needs.versions.outputs.base }}
    #    path: |
    #      build/Release/**/*.dll
    #      build/Release/**/*.exe

#  create-testing:
#    if: github.ref == 'refs/heads/master' && github.event_name == 'push' || github.event_name == 'workflow_dispatch'
#    needs: [msvc, ubuntu] #, macos]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v7
#        with:
#          submodules: recursive
#
#      - name: Download Artifacts
#        uses: actions/download-artifact@v8
#
#      - name: Create binary archives
#        run: |
#          7z a -r ete-linux-x86.zip            ./linux-x86/* -x!*.so
#          7z a -r ete-linux-x86_64.zip         ./linux-x86_64/* -x!*.so
#          7z a -r ete-windows-msvc-x86.zip     ./windows-x86/* -x!*.dll
#          7z a -r ete-windows-msvc-x64.zip     ./windows-x64/* -x!*.dll
#          #7z a -r ete-macos-x86_64.zip         ./macos-x86_64/* -x!*_mac
#          7z a -r ete-linux-x86.zip            ./steam/steam_appid.txt
#          7z a -r ete-linux-x86_64.zip         ./steam/steam_appid.txt
#          7z a -r ete-windows-msvc-x86.zip     ./steam/steam_appid.txt
#          7z a -r ete-windows-msvc-x64.zip     ./steam/steam_appid.txt
#          #7z a -r ete-macos-x86_64.zip         ./steam/steam_appid.txt
#          mkdir -p etmain
#          mv -t  ./etmain/ ./linux-x86/*.so
#          mv -t  ./etmain/ ./linux-x86_64/*.so
#          mv -t  ./etmain/ ./windows-x86/*.dll
#          mv -t  ./etmain/ ./windows-x64/*.dll
#          #mv -t  ./etmain/ ./macos-x86_64/*_mac
#          cd etmain
#          7z a -r -tzip mp_bina.pk3      ./cgame*.so
#          7z a -r -tzip mp_bina.pk3      ./ui*.so
#          7z a -r -tzip mp_bina.pk3      ./cgame*.dll
#          7z a -r -tzip mp_bina.pk3      ./ui*.dll
#          #7z a -r -tzip mp_bina.pk3      ./cgame_mac
#          #7z a -r -tzip mp_bina.pk3      ./ui_mac
#          cd ..
#          7z a -r ete-etmain-mod-replacement-allplatform.zip      ./etmain/*.pk3
#          7z a -r ete-etmain-mod-replacement-allplatform.zip      ./etmain/*.so
#          7z a -r ete-etmain-mod-replacement-allplatform.zip      ./etmain/*.dll
#          #7z a -r ete-etmain-mod-replacement-allplatform.zip      ./etmain/*_mac
#
#      - name: Create Client Hashes
#        run: |
#          md5sum ./linux-x86/ete.x86 > ete.x86.md5
#          sha1sum ./linux-x86/ete.x86 > ete.x86.sha1
#          md5sum ./linux-x86_64/ete.x86_64 > ete.x86_64.md5
#          sha1sum ./linux-x86_64/ete.x86_64 > ete.x86_64.sha1
#          md5sum ./windows-x86/ETe.exe > ETe.exe.md5
#          sha1sum ./windows-x86/ETe.exe > ETe.exe.sha1
#          md5sum ./windows-x64/ETe.x64.exe > ETe.x64.exe.md5
#          sha1sum ./windows-x64/ETe.x64.exe > ETe.x64.exe.sha1
#          md5sum ./windows-x86/ETe-vulkan.exe > ETe-vulkan.exe.md5
#          sha1sum ./windows-x86/ETe-vulkan.exe > ETe-vulkan.exe.sha1
#          md5sum ./windows-x64/ETe-vulkan.x64.exe > ETe-vulkan.x64.exe.md5
#          sha1sum ./windows-x64/ETe-vulkan.x64.exe > ETe-vulkan.x64.exe.sha1
#          #md5sum ./macos-x86_64/ete.x86_64 > ete_mac.x86_64.md5
#          #sha1sum ./macos-x86_64/ete.x86_64 > ete_mac.x86_64.sha1
#          7z a -r ete-client-hashes.zip *.md5 *.sha1
#
##TODO other builds
##NOTE purposely skipping etmain for macos as it is not really functional
##7z a -r ete-windows-mingw-x86.zip    ./windows-mingw-x86/* -x!*.dll
##7z a -r ete-windows-mingw-x86_64.zip ./windows-mingw-x86_64/* -x!*.dll
##7z a -r ete-windows-msvc-arm64.zip   ./windows-arm64/* -x!*.dll
##7z a -r ete-macos-arm64.zip         ./macos-arm64/* -x!*.dylib
##7z a -r ete-linux-aarch64.zip  ./linux-aarch64/*
##7z a -r ete-linux-armv7.zip    ./linux-armv7/*
##7z a -r -tzip mp_bina.pk3      ./*.dylib
#
#      - name: Create docs archive
#        run: |
#          7z a -r ete-docs.zip ./docs/*
#
#      - name: Create latest build
#        uses: czietz/action-automatic-releases@latest
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          automatic_release_tag: "latest"
#          prerelease: false
#          title: Latest Build
#          files: |
#            *.zip
#